project_id = "bonpqttgwunghfkgsiul"

[functions.ai-insights]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.clean-mpesa]
verify_jwt = false

[functions.detect-fraud]
verify_jwt = false

[functions.export-transactions]
verify_jwt = false

[functions.auth-proxy]
verify_jwt = false

[functions.ai-form-builder]
verify_jwt = true

[functions.publish-form]
verify_jwt = true

[functions.validate-mpesa-code]
verify_jwt = false

[functions.submit-public-form]
verify_jwt = false

[functions.send-email]
verify_jwt = false
